// packages/solid/src/model.use.ts
import { Model } from '@expressive/mvc';
import { onCleanup } from 'solid-js';

import { signalProxy } from './signals';

declare module '@expressive/mvc' {
  namespace Model {
    function use <T extends Model> (
      this: Model.Init<T>,
      apply?: Model.Assign<T>
    ): Model.Reactive<T>;
  }
}

Model.use = function <T extends Model> (
  this: Model.Init<T>,
  argument?: Model.Assign<T>){
 
  const instance = this.new(argument);
  const proxy = signalProxy(instance);

  onCleanup(() => instance.set(null));
  
  return proxy;
}

// packages/react/src/model.use.ts
import { Model, Context, createEffect } from '@expressive/mvc';

import { React } from './compat';

declare module '@expressive/mvc' {
  namespace Model {
    function use <T extends Model> (this: Model.Init<T>, ...args: Argument<T>[]): T;
  }
}

interface Compat extends Model {
  render?(...props: Model.Argument<this>[]): React.ReactNode;
  fallback?: React.ReactNode;
}

Model.use = function <T extends Compat> (
  this: Model.Init<T>,
  ...args: Model.Argument<T>[]){

  const context = Context.use(true);
  const state = React.useState(() => {
    let ready: boolean | undefined;
    let local: T;

    const instance = new this(...args);

    context.include(instance);
  
    const unwatch = createEffect(instance, current => {
      local = current;

      if(ready) 
        state[1](x => x.bind(null));
    });

    function didMount(){
      ready = true;
      return () => {
        unwatch();
        context.pop()
        instance.set(null);
      }
    }

    return (...args: Model.Argument<T>[]) => {
      React.useEffect(didMount, []);

      ready = false;
      Promise.all(args.map(arg => {
        if(typeof arg == "object")
          return instance.set(arg as Model.Assign<T>);
      })).then(() => ready = true);

      if(instance.render)
        instance.render(...args);

      return local; 
    };
  });

  return state[0](...args);
}
