// packages/react/src/state.ts
import { State, Context, watch, event } from '@expressive/mvc';
import { ReactNode } from 'react';
import { provide, Layers } from './context';
import type { AsComponent, HasProps, Props } from './component';

export const Pragma = {} as {
  useState<S>(initial: () => S): [S, (next: (previous: S) => S) => void];
  useEffect(effect: () => () => void, deps?: any[]): void;
  createElement(type: any, props?: any, ...children: any[]): any;
};

/** Type may not be undefined - instead will be null.  */
type NoVoid<T> = T extends undefined | void ? null : T;

const OUTER = new WeakMap<object, Context>();
const PROPS = new WeakMap<object, ReactState.ComponentProps<any>>();

type ForceRefresh = {
  /** Request a refresh for current component. */
  (): void;

  /**
   * Request a refresh and again after promise either resolves or rejects.
   *
   * @param waitFor Promise to wait for.
   * @returns Promise which resolves, after refresh, to same value as `waitFor`.
   */
  <T = void>(waitFor: Promise<T>): Promise<T>;

  /**
   * Request refresh before and after async function.
   * A refresh will occur both before and after the given function.
   *
   * **Note:** Any actions performed before first `await` will occur prior to refresh.
   *
   * @param invoke Async function to invoke.
   * @returns Promise which resolves returned value after refresh.
   */
  <T = void>(invoke: () => Promise<T>): Promise<T>;
};

type GetFactory<T extends State, R> = (
  this: T,
  current: T,
  refresh: ForceRefresh
) => R;

type GetEffect<T extends State> = (
  this: T,
  current: T,
  refresh: ForceRefresh
) => null;

type UseArgs<T extends State> = T extends {
  use(...props: infer P): any;
}
  ? P
  : State.Args<T>;

interface Renderable extends ReactState {
  readonly props: ReactState.ComponentProps<this>;
  context: Context;
  state: State.Values<this>;
  fallback?: ReactNode;

  render(): ReactNode;

  /** @deprecated Only for React JSX compatibility in typescript and nonfunctional. */
  setState: (state: any, callback?: () => void) => void;

  /** @deprecated Only for React JSX compatibility in typescript and nonfunctional. */
  forceUpdate: (callback?: () => void) => void;
}

declare namespace ReactState {
  export import Extends = State.Extends;
  export import Type = State.Type;
  export import Args = State.Args;
  export import Init = State.Init;
  export import Assign = State.Assign;
  export import Field = State.Field;
  export import Event = State.Event;
  export import Export = State.Export;
  export import Value = State.Value;
  export import Setter = State.Setter;
  export import OnEvent = State.OnEvent;
  export import OnUpdate = State.OnUpdate;
  export import Values = State.Values;
  export import Partial = State.Partial;
  export import Ref = State.Ref;
  export import Effect = State.Effect;
  export import EffectCallback = State.EffectCallback;

  export { GetFactory, GetEffect, UseArgs, HasProps, Renderable };
}

abstract class ReactState extends State {
  /**
   * Optional hook is called when State.use() is invoked within a React component.
   *
   * This is called *every render* of the component, and will intercept
   * arguments which would otherwise be merged into the State.
   *
   * @param props Arguments passed to State.use().
   */
  protected use?(...props: any[]): Promise<void> | void;

  /**
   * Create and manage instance of this State within React component.
   *
   * @param args Arguments to pass to constructor or `use` method (if defined).
   * @returns Managed instance of this State.
   */
  static use<T extends ReactState>(
    this: State.Type<T>,
    ...args: UseArgs<T>
  ): T {
    const ambient = Context.use();
    const state = Pragma.useState(() => {
      let ready: boolean | undefined;
      let active: T;

      let use = (...args: State.Args<T>): Promise<unknown> | void =>
        Promise.all(
          args
            .flat()
            .map(
              (arg) =>
                typeof arg == 'object' && instance.set(arg as State.Assign<T>)
            )
        );

      // Create instance - pass args to constructor if no use method
      const instance = new this((x) => {
        if (x instanceof ReactState && x.use) {
          use = x.use?.bind(x);
          use(...args);
        } else return args;
      });

      const context = ambient.push(instance);

      watch(instance, (current) => {
        active = current;

        if (ready) state[1]((x) => x.bind(null));
      });

      function didMount() {
        ready = true;
        return () => {
          context.pop();
          instance.set(null);
        };
      }

      return (...args: State.Args<T>) => {
        Pragma.useEffect(didMount, []);

        if (ready) {
          ready = false;

          Promise.resolve(use(...args)).finally(() => (ready = true));
        }

        return active;
      };
    });

    return state[0](...args);
  }

  /** Fetch instance of this class from context. */
  static get<T extends State>(this: State.Extends<T>): T;

  /** Fetch instance of this class optionally. */
  static get<T extends State>(
    this: State.Extends<T>,
    required: false
  ): T | undefined;

  /** Fetch instance of this class from context. */
  static get<T extends State>(
    this: State.Extends<T>,
    requireValues: true
  ): Required<T>;

  static get<T extends State, R>(
    this: State.Extends<T>,
    factory: GetFactory<T, Promise<R> | R>
  ): NoVoid<R>;

  // TODO: eagerly match this so any nulls are caught - would prevent updates.
  static get<T extends State>(
    this: State.Extends<T>,
    factory: GetEffect<T>
  ): null;

  static get<T extends State, R>(
    this: State.Extends<T>,
    argument?: boolean | GetFactory<T, unknown>
  ) {
    const context = Context.use();
    const state = Pragma.useState(() => {
      const instance = context.get(this);

      if (!instance)
        if (argument === false) return () => undefined;
        else throw new Error(`Could not find ${this} in context.`);

      let ready: boolean | undefined;
      let value: any;

      function render() {
        state[1]((x) => x.bind(null));
      }

      function refresh<T>(action?: Promise<T> | (() => Promise<T>)): any {
        if (typeof action == 'function') action = action();

        render();

        if (action) return action.finally(render);
      }

      const unwatch = watch(
        instance,
        (current) => {
          if (typeof argument === 'function') {
            const next = argument.call(current, current, refresh);

            if (next === value) return;

            value = next;
          } else value = current;

          if (ready) render();
        },
        argument === true
      );

      if (value instanceof Promise) {
        let error: Error | undefined;

        unwatch();

        value
          .then(
            (x) => (value = x),
            (e) => (error = e)
          )
          .finally(render);

        value = null;

        return () => {
          if (error) throw error;

          return value === undefined ? null : value;
        };
      }

      if (value === null) {
        unwatch();
        return () => null;
      }

      function onMount() {
        ready = true;
        return unwatch;
      }

      return () => {
        Pragma.useEffect(onMount, []);
        return value === undefined ? null : value;
      };
    });

    return state[0]() as R;
  }

  static as<T extends State, P extends State.Assign<T>>(
    this: State.Type<T>,
    render: (props: P, self: T) => ReactNode
  ) {
    const Type = this as unknown as State.Type<State>;
    const Self = new WeakMap<Component, React.FC>();

    class Component extends Type implements Renderable {
      static contextType = Layers;

      get props() {
        return PROPS.get(this) || {};
      }

      private set props(props: ReactState.ComponentProps<this>) {
        PROPS.set(this, props);
        this.set(props as {});
      }

      get context() {
        return Context.get(this)!;
      }

      set context(context: Context) {
        if (OUTER.get(this) === context) return;

        OUTER.set(this, context);
        context.push(this);
      }

      state = {} as State.Values<this>;
      fallback?: ReactNode = undefined;

      constructor({ is, ...props }: any) {
        super(props, is);
        // PROPS.set(this, props);
        Self.set(this, Render.bind(this, render as any));
      }

      render(): ReactNode {
        return Pragma.createElement(Self.get(this)!);
      }

      /** @deprecated Only for React JSX compatibility in typescript and nonfunctional. */
      setState!: (state: any, callback?: () => void) => void;

      /** @deprecated Only for React JSX compatibility in typescript and nonfunctional. */
      forceUpdate!: (callback?: () => void) => void;
    }

    Object.defineProperties(Component.prototype, {
      isReactComponent: {
        get: () => true
      },
      name: {
        value: this.name
      }
    });

    return Component as unknown as State.Type<T & Renderable>;
  }
}

function Render<T extends Renderable, P extends State.Assign<T>>(
  this: T,
  render: (props: P, self: T) => ReactNode
) {
  const state = Pragma.useState(() => {
    event(this);

    const { context } = this;

    let ready: boolean | undefined;
    let active: T;

    watch(this, (current) => {
      active = current;

      if (ready) state[1]((x) => x.bind(null));
    });

    const didMount = () => {
      ready = true;
      return () => {
        context.pop();
        this.set(null);
      };
    };

    const View = () => render.call(active, active.props as any, active);

    return () => {
      ready = false;

      Pragma.useEffect(didMount, []);
      setTimeout(() => (ready = true), 0);

      return provide(
        context,
        Pragma.createElement(View),
        active.fallback,
        String(this)
      );
    };
  });

  return state[0]();
}

export { ReactState };
export { AsComponent, Props };

// packages/solid/src/state.ts
import { State, listener, watch } from '@expressive/mvc';
import {
  Accessor,
  Signal,
  createSignal,
  onCleanup,
  useContext
} from 'solid-js';

import { Lookup } from './context';

/** Type may not be undefined - instead will be null. */
type NoVoid<T> = T extends undefined | void ? null : T;

declare module '@expressive/mvc' {
  interface UseState extends State {
    /**
     * Optional hook called when State.use() is invoked within a Solid component.
     *
     * Unlike React, Solid components run setup only once, so this is called a
     * single time and will intercept arguments which would otherwise be passed
     * into the State constructor.
     *
     * @param props Arguments passed to State.use().
     */
    use?(...props: any[]): Promise<void> | void;
  }

  namespace State {
    /**
     * Reactive proxy over a State instance. All non-function properties are
     * replaced by Solid signal accessors; methods and `is` pass through as-is.
     */
    type Reactive<T extends State> = {
      [P in keyof T]: P extends keyof State
        ? T[P]
        : T[P] extends (...args: any[]) => any
          ? T[P]
          : Accessor<T[P]>;
    };

    type ForceRefresh = {
      /** Notify subscribers of the returned accessor. */
      (): void;

      /**
       * Notify subscribers and again after promise either resolves or rejects.
       *
       * @param waitFor Promise to wait for.
       * @returns Promise which resolves, after refresh, to same value as `waitFor`.
       */
      <T = void>(waitFor: Promise<T>): Promise<T>;

      /**
       * Notify subscribers before and after async function.
       *
       * **Note:** Any actions performed before first `await` will occur prior to refresh.
       *
       * @param invoke Async function to invoke.
       * @returns Promise which resolves returned value after refresh.
       */
      <T = void>(invoke: () => Promise<T>): Promise<T>;
    };

    type GetFactory<T extends State, R> = (
      this: T,
      current: T,
      refresh: ForceRefresh
    ) => R;

    type GetEffect<T extends State> = (
      this: T,
      current: T,
      refresh: ForceRefresh
    ) => null;

    type UseArgs<T extends State> = T extends {
      use(...props: infer P): any;
    }
      ? P
      : State.Args<T>;

    /**
     * Create and manage an instance of this State within a Solid component.
     *
     * The instance is pushed onto ambient context, so `get()` instructions
     * within may resolve parent and peer states. It is destroyed on cleanup.
     *
     * @param args Arguments to pass to constructor or `use` method (if defined).
     * @returns Reactive proxy for managed instance of this State.
     */
    function use<T extends UseState>(
      this: State.Type<T>,
      ...args: UseArgs<T>
    ): Reactive<T>;

    /** Fetch instance of this class from context. Throws if not found. */
    function get<T extends State>(this: State.Extends<T>): Reactive<T>;

    /** Fetch instance of this class optionally. */
    function get<T extends State>(
      this: State.Extends<T>,
      required: false
    ): Reactive<T> | undefined;

    /**
     * Fetch instance of this class from context.
     * Accessors will throw if a value they refer to is undefined.
     */
    function get<T extends State>(
      this: State.Extends<T>,
      requireValues: true
    ): Reactive<Required<T>>;

    /**
     * Compute a value from instance of this class found in context.
     * Factory is run again (and accessor subscribers notified) when
     * any accessed properties update.
     *
     * If factory returns a promise, accessor will return null until it
     * settles - then the resolved value, or throw the rejection reason.
     */
    function get<T extends State, R>(
      this: State.Extends<T>,
      factory: GetFactory<T, Promise<R> | R>
    ): Accessor<NoVoid<R>>;

    /**
     * Run an effect against instance of this class found in context.
     * Returning null stops the effect from re-running.
     */
    function get<T extends State>(
      this: State.Extends<T>,
      factory: GetEffect<T>
    ): Accessor<null>;
  }
}

const PROXY = new WeakMap<object, State.Reactive<any>>();
const REQUIRED = new WeakMap<object, State.Reactive<any>>();
const SIGNALS = new WeakMap<object, Map<string, Signal<unknown>>>();

/**
 * Reactive proxy for any observable instance, where non-function properties
 * are served as Solid signal accessors.
 *
 * One proxy and one update listener exist per instance - repeat calls return
 * the cached proxy. The listener detaches automatically when the instance is
 * destroyed; caches are weakly held, so neither will leak.
 */
function signalProxy<T extends State>(
  from: T,
  requireValues?: boolean
): State.Reactive<T> {
  const subject = (from.is || from) as T;
  const cache = requireValues ? REQUIRED : PROXY;
  const cached = cache.get(subject);

  if (cached) return cached;

  let signals = SIGNALS.get(subject);

  if (!signals) {
    const update = signals = new Map<string, Signal<unknown>>();

    SIGNALS.set(subject, signals);

    listener(subject, (key) => {
      if (key === null) return null;

      if (typeof key === 'boolean') return;

      const signal = update.get(key as string);

      if (signal) signal[1](() => (subject as any)[key]);
    });
  }

  const required = requireValues
    ? new Map<string, Accessor<unknown>>()
    : undefined;

  const proxy = new Proxy(subject, {
    get(target: any, prop: string | symbol) {
      const value = target[prop];

      if (
        typeof value === 'function' ||
        typeof prop === 'symbol' ||
        prop === 'is'
      )
        return value;

      let signal = signals!.get(prop);

      if (!signal) {
        signal = createSignal(value, { equals: false });
        signals!.set(prop, signal);
      }

      if (!required) return signal[0];

      let accessor = required.get(prop);

      if (!accessor) {
        const read = signal[0];

        accessor = () => {
          const current = read();

          if (current === undefined)
            throw new Error(`${target}.${prop} is required in this context.`);

          return current;
        };

        required.set(prop, accessor);
      }

      return accessor;
    }
  }) as State.Reactive<T>;

  cache.set(subject, proxy);

  return proxy;
}

State.use = function use<T extends State>(
  this: State.Type<T>,
  ...args: State.UseArgs<T>
) {
  const ambient = useContext(Lookup);

  const instance: T = new this((x: any) => {
    if ('use' in x && typeof x.use === 'function') x.use(...args);
    else return args;
  });

  const context = ambient.push(instance);

  onCleanup(() => {
    context.pop();
    instance.set(null);
  });

  return signalProxy(instance);
};

State.get = function get<T extends State>(
  this: State.Extends<T>,
  argument?: boolean | State.GetFactory<T, unknown>
): any {
  const context = useContext(Lookup);

  if (typeof argument !== 'function') {
    const instance = context.get(this, argument);

    return instance ? signalProxy(instance, argument === true) : undefined;
  }

  const instance = context.get(this) as T;
  const [signal, setSignal] = createSignal(undefined, { equals: false });

  let value: any;
  let error: Error | undefined;

  function refresh<R>(action?: Promise<R> | (() => Promise<R>)): any {
    if (typeof action === 'function') action = action();

    setSignal(undefined);

    if (action instanceof Promise)
      return action.finally(() => setSignal(undefined));
  }

  const release = watch(instance, (current, changed) => {
    const next = argument.call(current, current, refresh);

    if (next === value) return;

    value = next;

    if (changed.length) setSignal(undefined);
  });

  if (value === null) {
    release();
    return () => null;
  }

  if (value instanceof Promise) {
    release();

    value
      .then(
        (x) => (value = x),
        (e) => (error = e)
      )
      .finally(() => setSignal(undefined));

    value = null;

    return () => {
      signal();

      if (error) throw error;

      return value === undefined ? null : value;
    };
  }

  onCleanup(release);

  return () => {
    signal();
    return value === undefined ? null : value;
  };
};

export { State, signalProxy };
